"""Automated Firmware Code Generator for Embedded Microcontrollers.
Generates complete, ready-to-flash C++ (Arduino/ESP-IDF) and MicroPython
driver initialization scripts with exact pin assignments, bus clocks, and device addresses.
"""

from __future__ import annotations
from typing import List, Dict, Any
from src.engine.circuit_validator import COMPONENT_REGISTRY


def generate_arduino_cpp(host_mcu: str, peripherals: List[str]) -> str:
    """Generates complete Arduino/C++ code with pin macros, Wire/SPI setup, and sensor init."""
    mcu_meta = COMPONENT_REGISTRY.get(host_mcu, {})
    i2c_pins = mcu_meta.get("default_i2c_pins", {"SDA": "21", "SCL": "22"})
    spi_pins = mcu_meta.get("default_spi_pins", {"MOSI": "23", "MISO": "19", "SCK": "18", "CS": "5"})

    lines = [
        "// ===========================================================================",
        f"// Hardware Initialization Code for {host_mcu}",
        f"// Peripherals: {', '.join(peripherals)}",
        "// Generated by Datasheet Engineering Intelligence Suite",
        "// ===========================================================================",
        "#include <Arduino.h>",
        "#include <Wire.h>",
        "#include <SPI.h>",
        "",
        "// ---------------- Pin Definitions ----------------",
    ]

    # Clean pin names (e.g. GPIO21 -> 21)
    sda_num = i2c_pins.get("SDA", "21").replace("GPIO", "").split()[0]
    scl_num = i2c_pins.get("SCL", "22").replace("GPIO", "").split()[0]
    lines.append(f"#define PIN_I2C_SDA {sda_num}")
    lines.append(f"#define PIN_I2C_SCL {scl_num}")

    has_i2c = False
    has_spi = False

    for p in peripherals:
        p_meta = COMPONENT_REGISTRY.get(p, {})
        interface = p_meta.get("interface", "")
        if "I2C" in interface:
            has_i2c = True
            addr = p_meta.get("default_i2c", "0x00")
            lines.append(f"#define ADDR_{p.upper()} {addr}")
        if "SPI" in interface:
            has_spi = True

    lines.extend([
        "",
        "void setup() {",
        "    Serial.begin(115200);",
        "    while (!Serial && millis() < 3000);",
        f'    Serial.println(F("🚀 Initializing {host_mcu} Hardware System..."));',
        "",
    ])

    if has_i2c:
        lines.extend([
            "    // Initialize I2C Bus at 400 kHz Fast-Mode",
            f"    Wire.begin(PIN_I2C_SDA, PIN_I2C_SCL);",
            "    Wire.setClock(400000);",
            '    Serial.println(F("✓ I2C Bus initialized at 400kHz"));',
            "",
            "    // Scan and verify connected I2C devices",
        ])
        for p in peripherals:
            p_meta = COMPONENT_REGISTRY.get(p, {})
            if "I2C" in p_meta.get("interface", ""):
                addr = p_meta.get("default_i2c", "0x00")
                lines.extend([
                    f"    Wire.beginTransmission(ADDR_{p.upper()});",
                    f"    if (Wire.endTransmission() == 0) {{",
                    f'        Serial.println(F("  [OK] {p} detected at address {addr}"));',
                    f"    }} else {{",
                    f'        Serial.println(F("  [WARN] {p} not responding at address {addr}!"));',
                    f"    }}",
                ])

    if has_spi:
        lines.extend([
            "",
            "    // Initialize SPI Bus",
            "    SPI.begin();",
            '    Serial.println(F("✓ SPI Bus initialized"));',
        ])

    lines.extend([
        "",
        '    Serial.println(F("✅ System hardware configuration complete."));',
        "}",
        "",
        "void loop() {",
        "    // Periodic telemetry loop",
        "    delay(1000);",
        "}",
    ])
    return "\n".join(lines)


def generate_micropython_code(host_mcu: str, peripherals: List[str]) -> str:
    """Generates complete MicroPython initialization script."""
    mcu_meta = COMPONENT_REGISTRY.get(host_mcu, {})
    i2c_pins = mcu_meta.get("default_i2c_pins", {"SDA": "GPIO21", "SCL": "GPIO22"})

    sda_num = i2c_pins.get("SDA", "21").replace("GPIO", "").split()[0]
    scl_num = i2c_pins.get("SCL", "22").replace("GPIO", "").split()[0]

    lines = [
        "# ===========================================================================",
        f"# MicroPython Hardware Driver for {host_mcu}",
        f"# Peripherals: {', '.join(peripherals)}",
        "# Generated by Datasheet Engineering Intelligence Suite",
        "# ===========================================================================",
        "import machine",
        "import time",
        "",
        f"# Configure I2C Bus on {host_mcu}",
        f"i2c = machine.I2C(0, scl=machine.Pin({scl_num}), sda=machine.Pin({sda_num}), freq=400000)",
        "",
        "def scan_and_init():",
        f"    print('🚀 Initializing {host_mcu} Hardware System...')",
        "    devices = [hex(x) for x in i2c.scan()]",
        "    print(f'✓ Detected I2C addresses on bus: {devices}')",
        "",
    ]

    for p in peripherals:
        p_meta = COMPONENT_REGISTRY.get(p, {})
        if "I2C" in p_meta.get("interface", ""):
            addr = p_meta.get("default_i2c", "0x00")
            lines.append(f"    if '{addr.lower()}' in devices or {addr} in i2c.scan():")
            lines.append(f"        print('  [OK] {p} is responding at {addr}')")
            lines.append("    else:")
            lines.append(f"        print('  [WARN] {p} not detected at {addr}!')")

    lines.extend([
        "",
        "if __name__ == '__main__':",
        "    scan_and_init()",
    ])
    return "\n".join(lines)
