"""EDA Netlist Exporter for Hardware Circuits.
Generates industry-standard KiCad v6+ Netlists (.net) and SPICE simulation netlists (.cir)
from verified pin-to-pin wiring connections and component definitions.
"""

from __future__ import annotations
from typing import List, Dict, Any
from src.engine.circuit_validator import COMPONENT_REGISTRY
from src.engine.wiring_assistant import generate_wiring_plan


def generate_kicad_netlist(host_mcu: str, peripherals: List[str]) -> str:
    """Generates an S-expression formatted KiCad PCB Netlist (.net)."""
    wiring = generate_wiring_plan(host_mcu, peripherals)
    all_comps = [host_mcu] + [p for p in peripherals if p != host_mcu]

    lines = [
        '(export (version "E")',
        '  (design',
        f'    (source "{host_mcu.lower()}_project.kicad_sch")',
        '    (tool "Datasheet Engine EDA Netlist Generator v2.0")',
        '  )',
        '  (components',
    ]

    # Components list
    for idx, comp in enumerate(all_comps, start=1):
        meta = COMPONENT_REGISTRY.get(comp, {})
        footprint = "Package_DIP:DIP-16_W7.62mm" if "Op-Amp" in meta.get("family", "") else "Module:Breakout_Generic"
        lines.append(f'    (comp (ref "U{idx}")')
        lines.append(f'      (value "{comp}")')
        lines.append(f'      (footprint "{footprint}")')
        lines.append(f'      (property (name "Voltage") (value "{meta.get("voltage", "3.3")}V"))')
        lines.append(f'      (property (name "Family") (value "{meta.get("family", "IC")}"))')
        lines.append('    )')
    lines.append('  )')

    # Nets list
    lines.append('  (nets')
    net_id = 1

    # Group connections by net name
    for w in wiring.get("wiring_table", []):
        sig = w["Signal Type"].replace(" ", "_")
        s_comp = w["Source Component"]
        s_pin = w["Source Pin"].split()[0]
        t_comp = w["Target Component"]
        t_pin = w["Target Pin"].split()[0]

        net_name = f"Net-(U_{s_comp}-{s_pin})"
        if "Power" in sig:
            net_name = f"+{w['Source Pin'].split()[0]}"
        elif "Ground" in sig:
            net_name = "GND"
        elif "I2C" in sig:
            net_name = f"I2C_{t_pin}"

        lines.append(f'    (net (code "{net_id}") (name "{net_name}")')
        lines.append(f'      (node (ref "U1") (pin "{s_pin}"))')
        target_idx = all_comps.index(t_comp) + 1 if t_comp in all_comps else 2
        lines.append(f'      (node (ref "U{target_idx}") (pin "{t_pin}"))')
        lines.append('    )')
        net_id += 1

    lines.append('  )')
    lines.append(')')
    return "\n".join(lines)


def generate_spice_netlist(host_mcu: str, peripherals: List[str]) -> str:
    """Generates a standard SPICE simulation netlist (.cir) with DC supply rails and loads."""
    wiring = generate_wiring_plan(host_mcu, peripherals)
    all_comps = [host_mcu] + [p for p in peripherals if p != host_mcu]

    lines = [
        f"* SPICE Netlist for {host_mcu} Hardware System",
        "* Generated by Datasheet Engineering Intelligence Suite",
        "",
        "* Power Supply Sources",
        "VCC_3V3 VCC_3V3 0 DC 3.3",
        "VCC_5V0 VCC_5V0 0 DC 5.0",
        "",
        "* Component Subcircuits & Passive Pull-ups",
    ]

    for comp in peripherals:
        meta = COMPONENT_REGISTRY.get(comp, {})
        current = meta.get("current_ma", 5.0)
        equiv_res = round((3.3 / max(current * 1e-3, 1e-4)), 1)
        lines.append(f"* {comp} Load Model (Current ~ {current} mA)")
        lines.append(f"R_{comp}_LOAD VCC_3V3 0 {equiv_res}")

        if "I2C" in meta.get("interface", ""):
            lines.append(f"* I2C Pull-up resistors for {comp}")
            lines.append(f"R_PU_SDA VCC_3V3 SDA 4.7k")
            lines.append(f"R_PU_SCL VCC_3V3 SCL 4.7k")

    lines.extend([
        "",
        "* Transient Simulation Commands",
        ".tran 0.1m 10m",
        ".control",
        "run",
        "plot v(VCC_3V3)",
        ".endc",
        ".end",
    ])
    return "\n".join(lines)
